
export const FETCH_CAMPAIGNS_REQUEST = 'FETCH_CAMPAIGNS_REQUEST';
export const FETCH_CAMPAIGNS_SUCCESS = 'FETCH_CAMPAIGNS_SUCCESS';
export const FETCH_CAMPAIGNS_ERROR   = 'FETCH_CAMPAIGNS_ERROR';

export const SET_CURRENT_CAMPAIGN_NAME       = 'SET_CURRENT_CAMPAIGN_NAME';
export const SET_CURRENT_CAMPAIGN_SETTINGS   = 'SET_CURRENT_CAMPAIGN_SETTINGS';
export const SET_CURRENT_CAMPAIGN_DATA       = 'SET_CURRENT_CAMPAIGN_DATA';
